# Using Ecological Foreccasts to Guide Decision Making

Because of increased variability in populations, communities, and ecosystems due to land use and climate change, there is a pressing need to know the future state of ecological systems across space and time. Ecological forecasting is an emerging approach which provides an estimate of the future state of an ecological system with uncertainty, allowing society to preemptively prepare for fluctuations in important ecosystem services. However, forecasts must be effectively designed and communicated to those who need them to realize their potential for protecting natural resources. In this module, students will explore real ecological forecast visualizations, identify ways to represent uncertainty, make management decisions using forecast visualizations and learn decision support techniques. Lastly, students will then customize a forecast visualization for a specific forecast user's decision needs. The overarching goal of this module is for students to understand how forecasts are connected to decision-making of forecast users, or the managers, policy-makers, and other members of society who use forecasts to inform decision-making.

Background presentation: <https://cdn.serc.carleton.edu/files/eddie/teaching_materials/modules/instructor_powerpoint_module8.pptx>

Rshiny App (includes Assignment): <https://macrosystemseddie.shinyapps.io/module8/>

This module was developed by W.M. Woelmer, R.Q. Thomas, T.N. Moore and C.C. Carey. 21 January 2021. Macrosystems EDDIE: Using Ecological Forecasts to Guide Decision-Making. Macrosystems EDDIE Module 8, Version 1. http://module8.macrosystemseddie.org. Module development was supported by NSF grants DEB-1926050 and DBI-1933016.

This module has been peer-reviewed and included in the "On the Cutting Edge Exemplary Teaching Activities" collection.

Reference describing the effectiveness of the module:

Woelmer, W.M., T.N. Moore, M.E. Lofton, R.Q. Thomas, and C.C. Carey. 2023. Embedding communication concepts in forecasting training increases students' understanding of ecological uncertainty Ecosphere 14: e4628 <https://doi.org/10.1002/ecs2.4628>
