# First forecast: Introduction to NEON Ecological Forecasting Challenge {#sec-first-forecast}

This chapter, and the associated tutorial material, introduces participants to key concepts in ecological forecasting and provides hands-on materials for submitting forecasts to the Ecological Forecasting Initiative (EFI) - National Ecological Observatory Network (NEON) Forecasting Challenge (hereafter, Challenge). You can learn more about the Challenge in @thomasNEONEcologicalForecasting2023. The tutorial has been developed and used with more than 300 participants in both classrooms and workshops and provides the ecological understanding, workflows, and tools to enable ecologists with minimal forecasting experience to participate in the Challenge via a hands-on code-based tutorial. This R-based tutorial introduces participants to a near-term, iterative forecasting workflow that includes obtaining observations from NEON, developing a simple forecasting model, generating a forecast, and submitting the forecast to the Challenge, as well as analyzing forecast performance once new observations become available for evaluation. The overarching aim of this tutorial is to lower the barrier to ecological forecasting and empower participants to continue to innovate and develop their own ecological forecasts for the Challenge into the future.

The assignment will require you to create a GitHub repository with your completed code from the NEON Forecasting Challenge workshop. You will build on this repository throughout the rest of section 1 of the book. You can learn more about setting up Git and GitHub in @sec-github.

This tutorial was developed by Olsson, F., C. Boettiger, C.C. Carey, M.E. Lofton, and R.Q. Thomas

[**Tutorial**](https://github.com/OlssonF/NEON-forecast-challenge-workshop)

You will be generating forecasts of water temperature at NEON aquatics sites.

## Reading

Thomas, R. Q., Boettiger, C., Carey, C. C., Dietze, M. C., Johnson, L. R., Kenney, M. A., et al. (2023). The NEON Ecological Forecasting Challenge. Frontiers in Ecology and the Environment, 21(3), 112–113. <https://doi.org/10.1002/fee.2616>

## Assignment

Pre-assignment set up: Follow the [instructions for setting up R and the code repository](https://github.com/OlssonF/NEON-forecast-challenge-workshop#neon-forecast-challenge-workshop-pre-workshop-instructions)

1.  Create a GitHub repository with the module
2.  Work through the [`Submit_forecast/NEON_forecast_challenge_workshop_aquatics.Rmd`](https://github.com/OlssonF/NEON-forecast-challenge-workshop/blob/main/Submit_forecast/NEON_forecast_challenge_workshop_aquatics.Rmd) into TASKS sections
3.  Modify the simple model in the [`Submit_forecast/forecast_code_template.Rmd`](https://github.com/OlssonF/NEON-forecast-challenge-workshop/blob/main/Submit_forecast/forecast_code_template.Rmd) in some way (see TASKS for ideas).
4.  Add a brief description of what you changed to the beginning of the template.
5.  Knit the template Rmd to html.
6.  Commit template Rmd and html to GitHub

## Module reference

Olsson, F., C. Boettiger, C.C. Carey, M.E. Lofton, and R.Q. Thomas. Can you predict the future? A tutorial for the National Ecological Observatory Network Ecological Forecasting Challenge. In review at *Journal of Open Source Education*.
