# Welcome {.unnumbered}

This book is designed for a graduate class in ecological forecast (Virginia Tech graduate course FREC 5174: Ecological Modeling and Forecasting) and for use as a how-to-guide for ecological forecasting. It leverages work through the NSF-funded Macrosystems EDDIE (DEB-1926050) and Ecological Forecasting Initiative Research Coordination Network (DEB-1926388) projects. It includes training materials developed by the Macrosystems EDDIE forecasting team at Virginia Tech (Cayelan Carey, Mary Lofton, Tadhg Moore, Whitney Woelmer), Freya Olsson (NEON Ecological Forecasting Challenge workshop), Mike Dietze (Terrestrial carbon flux tutorial and modified activities from his Ecological Forecasting; @dietzeEcologicalForecasting2017), and John Smith (NEON carbon data processing code). The imprint of Carl Boettiger on the materials is throughout the book.

The book uses R code to teach concepts by example (hence the name "A practical guide"). The books includes very few equations because often I find myself wishing I had code to better understand equations in papers. It also uses a "from scratch" approach that provides code with the details of key algorithms (like Markov Chain Monte Carlo Metropolis Hastings and the boot strap particle filter). Future work on this book could add examples of how to implement the analyses using existing R packages (e.g., JAGS and Nimble). In practice, using these packages is better because they can improve provide efficiency and accuracy of estimates. Finally, there are few places where I make functions that hide some of the details but these are cases where the algorithm are highly specific to the application (e.g., access weather data from a specific server).

The book is a near-term iterative forecast itself. It automatically rebuilds every day using GitHub actions. Each build accesses the latest NEON data, NOAA weather forecasts, assimilated data, and generates a new forecast of daily net ecosystem exchange (NEE) for one NEON site (TALL). The forecast is submitted to the NEON Ecological Forecasting Challenge. As a result, the NEON data in [Chapter -@sec-neon] and the forecast in [Chapter -@sec-pulling-together] should be near real-time.

The terms ecosystem forecasting and ecological forecasting will be used interchangeability throughout the book. The use of ecosystem forecasting in the title reflects the focus on ecosystem-scale data in the book and to distinguish from Mike Dietze's excellent book called Ecological Forecasting @dietzeEcologicalForecasting2017.

The book is a work in progress that involves harmonizing materials developed for many different use-cases (undergraduate courses, tutorials, graduate classes). As a result there are likely to differences among chapters in style and approaches to assignments.

I welcome feedback on the book through GitHub issues and/or Pull Requests.
