install.packages("MODISTools")
install.packages("scoringRules")
install.packages("patchwork")
install.packages("daymetr")
install.packages("neonstore")
install.packages("duckdbfs")
remotes::install_github("ropensci/allodb")
remotes::install_github("eco4cast/neon4cast")
