#install.packages("neonstore")
install.packages("MODISTools")
install.packages("scoringRules")
install.packages("patchwork")
install.packages("daymetr")
remotes::install_github("ropensci/allodb")
remotes::install_github("cboettig/neonstore")
install.packages("duckdbfs")
