# Introduction {#sec-intro}

{{< video https://www.youtube.com/embed/Lgi_e7N-C8E?si=lUwugeXg_oVTS8-u >}}

Welcome! The overarching goal of the course (and this book) is to teach concepts and skills in ecological modeling and forecasting and contribute forecasts to an international forecasting challenge run by the Ecological Forecasting Initiative and led out of Virginia Tech (@thomasNEONEcologicalForecasting2023). The NEON (National Ecological Observatory Network) Ecological Forecasting Challenge empowers teams to submit forecasts of NEON data before it is collected as a test of our capacity to predict ecological processes in the future. More information about the NEON Ecological Forecasting Challenge can be found here: neon4cast.org

The first half of the book will build the foundations of ecological forecasting using a set of modules, developed at Virginia Tech, that have been widely used and tested across the globe (@mooreIntegratingEcologicalForecasting2022, @woelmerEmbeddingCommunicationConcepts2023). Topics include an introduction to the iterative, near-term forecasting cycle, understanding uncertainty in ecological forecasts, using data to improve ecological forecasts, and using ecological forecasting to guide decision making. By the end of the first section, you will be automatically submitting forecasts that you developed to the NEON Ecological Forecasting Challenge. The first half will explicitly focus on forecasting using statistical/empirical models. In the process, you will gain skills in the use of GitHub, GitHub Actions, Docker, Tidymodels <https://www.tidymodels.org>), and Fable <https://fable.tidyverts.org>).

The second half of the book will introduce more advanced concepts in ecological modeling and forecasting by focusing on the use of process models (e.g., models that represent ecological mechanisms). We will learn how to build a process model, estimate the parameters of process models using likelihood and Bayesian techniques, and update the model using data assimilation.

Throughout the class you will work with multiple NEON data products that include water temperature, phenocam, chlorophyll-a and terrestrial carbon. [NEON]( https://www.neonscience.org) is a continental-scale observatory funded by the U.S. National Science Foundation to generate standardized measurements of ecological systems across 81 sites over the next 30-years. The data are freely available to use.

## Learning objectives

Having completed the course a student will be able to:

1.  Create computer models that mathematically represent an ecological system,
2.  Apply maximum likelihood methods to estimate parameters in ecological models using data,
3.  Apply Bayesian methods to estimate parameter distributions in ecological models using data,
4.  Apply sequential data assimilation to improve ecological model predictions, and
5.  Create, evaluate, and interpret an ecological forecast of the future that includes uncertainty.

## Readings

Clark, J. S., Carpenter, S. R., Barber, M., Collins, S., Dobson, A., Foley, J. A., et al. (2001). Ecological Forecasts: An Emerging Imperative. Science, 293(5530), 657–660. <https://doi.org/10.1126/science.293.5530.657>

Dietze, M., & Lynch, H. (2019). Forecasting a bright future for ecology. Frontiers in Ecology and the Environment, 17(1), 3–3. <https://doi.org/10.1002/fee.1994>

Thomas, R. Q., Boettiger, C., Carey, C. C., Dietze, M. C., Johnson, L. R., Kenney, M. A., et al. (2023). The NEON Ecological Forecasting Challenge. Frontiers in Ecology and the Environment, 21(3), 112–113. <https://doi.org/10.1002/fee.2616>










