# Parameter calibration: Applying to process model

```{r}
#| echo: FALSE
source("R/helpers.R")
```


```{r}
library(tidyverse)
library(patchwork)
set.seed(100)

#Set MCMC Configuration
num_iter <- 1000
num_pars <- 2
jump_params <- c(0.005, 0.001)
ens_members <- 1

log_likelihood_prior_current <- -10000000000
accept <- 0

sim_dates <- seq(as_date("2023-01-01"), as_date("2023-12-01"), by = "1 day")


params <- list()
params$alpha <- rep(0.02, ens_members)
params$SLA <- rep(4.74, ens_members)
params$leaf_frac <- rep(0.315, ens_members)
params$Ra_frac <- rep(0.5, ens_members)
params$Rbasal <- rep(0.002, ens_members)
params$Q10 <- rep(2.1, ens_members)
params$litterfall <- rep(1/(365*2), ens_members) #Two year leaf lifespan
params$mortality <- rep(0.00015, ens_members) #Wood lives about 18 years on average (all trees, branches, roots, course roots)
params$sigma.leaf <- rep(0.0, ens_members) #0.01 
params$sigma.stem <- rep(0.0, ens_members) #0.01 ## wood biomass
params$sigma.soil <- rep(0.0, ens_members)# 0.01
params <- as.data.frame(params)

#Initialize chain
fit_params <- array(NA, dim = c(num_pars, num_iter))
fit_params[1, 1] <- params$alpha
fit_params[2, 1] <- params$litterfall


state_init <- rep(NA, 3)

state_init[1] <- obs |> 
  filter(datetime %in% sim_dates,
         variable == "lai") |> 
  na.omit() |> 
  summarise(observation = mean(observation, na.rm = TRUE)) |> 
  mutate(observation = observation / (mean(params$SLA) * 0.1)) |> 
  pull(observation)

state_init[2] <- obs |> 
  filter(variable == "wood") |> 
  na.omit() |> 
  slice(1) |> 
  pull(observation)

state_init[3] <- obs |> 
  filter(variable == "som") |> 
  na.omit() |> 
  slice(1) |> 
  pull(observation)

inputs <- inputs_all |> 
    filter(datetime %in% sim_dates)
inputs_ensemble <- assign_met_ensembles(inputs, ens_members = 1)


for(iter in 2:num_iter){
  
  #Loop through parameter value
  
  for(j in 1:num_pars){
    
    proposed_pars <- fit_params[, iter - 1]
    proposed_pars[j] <- rnorm(1, mean = fit_params[j, iter - 1], sd = jump[j])
    
    log_prior <- dunif(proposed_pars[1], min = 0, max = 1, log = TRUE) + 
      dunif(proposed_pars[2], min = 0, max = 1, log = TRUE)
    
    params$alpha  <- proposed_pars[1]
    params$litterfall  <- proposed_pars[2]
    
    #Set initial conditions
    output <- array(NA, dim = c(length(sim_dates), ens_members, 12)) #12 is the number of outputs
    output[1, , 1] <- state_init[1]
    output[1, , 2] <- state_init[2]
    output[1, , 3] <- state_init[3]
    
    for(t in 2:length(sim_dates)){
      output[t, , ]  <- forest_model(t, 
                                     states = matrix(output[t-1 , , 1:3], nrow = ens_members) , 
                                     parms = params, 
                                     inputs = matrix(inputs_ensemble[t ,, ], nrow = ens_members))
    }
    
    output_df <- output_to_df(output, sim_dates, sim_name = "fitting")
    
    combined_output_obs <- combine_model_obs(output_df, 
                                             obs,
                                             variables = c("lai", "wood", "som", "nee"), 
                                             sds = c(0.5, 20, 20, 0.1))
    
    log_likelihood <- sum(dnorm(x =  combined_output_obs$observation, 
                                mean = combined_output_obs$prediction, 
                                sd = combined_output_obs$sds, log = TRUE))
    
    log_likelihood_prior_proposed <- log_prior + log_likelihood
    
    z <- exp(log_likelihood_prior_proposed - log_likelihood_prior_current)
    
    r <- runif(1, min = 0, max = 1)
    
    if(z >  r){
      fit_params[j, iter] <- proposed_pars[j]
      log_likelihood_prior_current <- log_likelihood_prior_proposed
      accept <- accept + 1
    }else{
      fit_params[j, iter] <- fit_params[j, iter - 1]
      log_likelihood_prior_current <- log_likelihood_prior_current #this calculation isn't necessary but is here to show you the logic
    }
  }
}

accept / (num_iter * num_pars)

```

```{r}
nburn <- 500
d <- tibble(iter = nburn:num_iter,
            par1 = fit_params[1, nburn:num_iter],
            par2 = fit_params[2, nburn:num_iter]) %>%
  pivot_longer(-iter, values_to = "value", names_to = "parameter")

p1 <- ggplot(d, aes(x = iter, y = value)) +
  geom_line() +
  facet_wrap(~parameter, scales = "free")

p2 <- ggplot(d, aes(x = value)) +
  geom_histogram() +
  facet_wrap(~parameter, scales = "free")

p1 / p2
```

```{r}
ens_members <- 1
#Set initial conditions
output <- array(NA, dim = c(length(sim_dates), ens_members, 12)) #12 is the number of outputs
output[1, , 1] <- state_init[1]
output[1, , 2] <- state_init[2]
output[1, , 3] <- state_init[3]


params <- list()
params$alpha <- rep(0.02, ens_members)
params$SLA <- rep(4.74, ens_members)
params$leaf_frac <- rep(0.315, ens_members)
params$Ra_frac <- rep(0.5, ens_members)
params$Rbasal <- rep(0.002, ens_members)
params$Q10 <- rep(2.1, ens_members)
params$litterfall <- rep(1/(365*2), ens_members) #Two year leaf lifespan
params$mortality <- rep(0.00015, ens_members) #Wood lives about 18 years on average (all trees, branches, roots, course roots)
params$sigma.leaf <- rep(0.0, ens_members) #0.01 
params$sigma.stem <- rep(0.0, ens_members) #0.01 ## wood biomass
params$sigma.soil <- rep(0.0, ens_members)# 0.01
params <- as.data.frame(params)

params$alpha <- rep(mean(fit_params[1, nburn:num_iter]), ens_members)
params$litterfall <- rep(mean(fit_params[2, nburn:num_iter]), ens_members)

#params$alpha <- sample(fit_params[1, nburn:num_iter], ens_members, replace = TRUE)
#params$litterfall <- sample(fit_params[2, nburn:num_iter], ens_members, replace = TRUE)

for(t in 2:length(sim_dates)){
  
  output[t, , ]  <- forest_model(t, 
                                 states = matrix(output[t-1 , , 1:3], nrow = ens_members) , 
                                 parms = params, 
                                 inputs = matrix(inputs_ensemble[t ,, ], nrow = ens_members))
}

output_df_optim <- output_to_df(output, sim_dates, sim_name = "optimized_mean")

```


```{r}
ens_members <- 100

#Set initial conditions
output <- array(NA, dim = c(length(sim_dates), ens_members, 12)) #12 is the number of outputs
output[1, , 1] <- state_init[1]
output[1, , 2] <- state_init[2]
output[1, , 3] <- state_init[3]

params <- list()
params$alpha <- rep(0.02, ens_members)
params$SLA <- rep(4.74, ens_members)
params$leaf_frac <- rep(0.315, ens_members)
params$Ra_frac <- rep(0.5, ens_members)
params$Rbasal <- rep(0.002, ens_members)
params$Q10 <- rep(2.1, ens_members)
params$litterfall <- rep(1/(365*2), ens_members) #Two year leaf lifespan
params$mortality <- rep(0.00015, ens_members) #Wood lives about 18 years on average (all trees, branches, roots, course roots)
params$sigma.leaf <- rep(0.0, ens_members) #0.01 
params$sigma.stem <- rep(0.0, ens_members) #0.01 ## wood biomass
params$sigma.soil <- rep(0.0, ens_members)# 0.01
params <- as.data.frame(params)

for(t in 2:length(sim_dates)){
  
  output[t, , ]  <- forest_model(t, 
                                 states = matrix(output[t-1 , , 1:3], nrow = ens_members) , 
                                 parms = params, 
                                 inputs = matrix(inputs_ensemble[t ,, ], nrow = ens_members))
}

output_df_no_optim <- output_to_df(output, sim_dates, sim_name = "no_optim")
```


```{r}
bind_rows(output_df_no_optim, output_df_optim) |> 
  filter(variable %in% c("lai", "wood", "som", "nee")) |> 
  mutate(ensemble = paste0(ensemble,"_",type)) |> 
  ggplot(aes(x = datetime)) +
  geom_line(aes(y = prediction, group = ensemble, color = type), alpha = 0.5) +
  #geom_point(data = obs, aes(x = datetime, y = observation), color = "red", alpha = 0.5) +
  facet_wrap(~variable, scale = "free")
```

```{r}

#Set initial conditions
output <- array(NA, dim = c(length(sim_dates), ens_members, 12)) #12 is the number of outputs
output[1, , 1] <- state_init[1]
output[1, , 2] <- state_init[2]
output[1, , 3] <- state_init[3]

params <- list()
params$alpha <- rep(0.02, ens_members)
params$SLA <- rep(4.74, ens_members)
params$leaf_frac <- rep(0.315, ens_members)
params$Ra_frac <- rep(0.5, ens_members)
params$Rbasal <- rep(0.002, ens_members)
params$Q10 <- rep(2.1, ens_members)
params$litterfall <- rep(1/(365*2), ens_members) #Two year leaf lifespan
params$mortality <- rep(0.00015, ens_members) #Wood lives about 18 years on average (all trees, branches, roots, course roots)
params$sigma.leaf <- rep(0.0, ens_members) #0.01 
params$sigma.stem <- rep(0.0, ens_members) #0.01 ## wood biomass
params$sigma.soil <- rep(0.0, ens_members)# 0.01
params <- as.data.frame(params)

#params$alpha <- rep(mean(fit_params[1, nburn:num_iter]), ens_members)
#params$litterfall <- rep(mean(fit_params[2, nburn:num_iter]), ens_members)

params$alpha <- sample(fit_params[1, nburn:num_iter], ens_members, replace = TRUE)
params$litterfall <- sample(fit_params[2, nburn:num_iter], ens_members, replace = TRUE)

for(t in 2:length(sim_dates)){
  
  output[t, , ]  <- forest_model(t, 
                                 states = matrix(output[t-1 , , 1:3], nrow = ens_members) , 
                                 parms = params, 
                                 inputs = matrix(inputs_ensemble[t ,, ], nrow = ens_members))
}

output_df_optim <- output_to_df(output, sim_dates, sim_name = "optimized")

```

```{r}
bind_rows(output_df_no_optim, output_df_optim) |> 
  filter(variable %in% c("lai", "wood", "som", "nee")) |> 
  mutate(ensemble = paste0(ensemble,"_",type)) |> 
  ggplot(aes(x = datetime)) +
  geom_line(aes(y = prediction, group = ensemble, color = type), alpha = 0.5) +
  #geom_point(data = obs, aes(x = datetime, y = observation), color = "red", alpha = 0.5) +
  facet_wrap(~variable, scale = "free")
```
