# Second forecast: Adding uncertainty to first forecast {#sec-second-forecast}

The forecast you generated in @sec-first-forecast included uncertainty introduced by the uncertainty in the future weather. As you learned in @sec-under-unc, there are many other sources of uncertainty that could be included in your forecast. Your task is to apply the techniques in @sec-under-unc to generate additional sources of uncertainty in the forecast model from @sec-first-forecast. When you are finished, your model from @sec-first-forecast should have driver, parameter, and process uncertainty. You will submit the assignment as an updated GitHub repository with the code and plot of your forecast with all uncertainty sources included.

You will be generating forecasts of water temperature at NEON aquatics sites.

A [version of the template](https://github.com/frec-5174/book-problem-sets/blob/main/forecast_code_template_mod6.Rmd) from @sec-first-forecast is provided that recodes the template to match the approach in @sec-under-unc.  You should add your model from @sec-first-forecast to this template before adding the uncertainty sources from @sec-under-unc.  

## Reading

Thomas, R. Q., Boettiger, C., Carey, C. C., Dietze, M. C., Johnson, L. R., Kenney, M. A., et al. (2023). The NEON Ecological Forecasting Challenge. Frontiers in Ecology and the Environment, 21(3), 112–113. <https://doi.org/10.1002/fee.2616>

## Assignment

Pre-assignment set up: Complete @sec-first-forecast and @sec-under-unc

1.  Modify your template code to include the additional sources of uncertainty
2.  Knit the template Rmd to html.
3.  Commit template and html to GitHub

## Module reference

Olsson, F., C. Boettiger, C.C. Carey, M.E. Lofton, and R.Q. Thomas. Can you predict the future? A tutorial for the National Ecological Observatory Network Ecological Forecasting Challenge. In review at *Journal of Open Source Education*.
