# Using data to improve ecological forecasts {#sec-eddiemod7}

To be useful for management, ecological forecasts need to be both accurate enough for managers to be able to rely on them for decision-making and include a representation of forecast uncertainty, so managers can properly interpret the probability of future events. To improve forecast accuracy by starting forecast current conditions, we can update forecasts with observational data once they become available, a process known as data assimilation. Recent improvements in environmental sensor technology and an increase in the number of sensors deployed in ecosystems have resulted in an increase in the availability of data for assimilation to help develop and improve forecasts for natural resource management. In this module, students will develop an ecosystem model of primary productivity, use the model to generate forecasts, and then explore how assimilating different types of data at different temporal frequencies (e.g., daily, weekly) affects forecast accuracy. Finally, students will assimilate different types of data into forecasts and examine how data assimilation affects water resource management decisions.

[**Background presentation**](https://cdn.serc.carleton.edu/files/eddie/teaching_materials/modules/instructors_powerpoint_23sep22.v4.pptx)

[**Rshiny App**](https://macrosystemseddie.shinyapps.io/module7/)

[**Assignment**](https://cdn.serc.carleton.edu/files/eddie/teaching_materials/modules/student_handout_23sep22.docx)

This module was developed by: Lofton, M.E., T.N. Moore, Thomas, R.Q., and C.C. Carey. 20 September 2022. Macrosystems EDDIE: Using Data to Improve Ecological Forecasts. Macrosystems EDDIE Module 7, Version 1. <https://macrosystemseddie.shinyapps.io/module7>. Module development was supported by NSF grants DEB-1926050 and DBI-1933016.

This module has been peer-reviewed and included in the ["On the Cutting Edge Exemplary Teaching Activities"](https://serc.carleton.edu/teachearth/exemplary.html) collection.

## Readings

Niu, S., Luo, Y., Dietze, M. C., Keenan, T. F., Shi, Z., Li, J., & III, F. S. C. (2014). The role of data assimilation in predictive ecology. Ecosphere, 5(5), art65-16. <https://doi.org/10.1890/ES13-00273.1>
